<template>
  <div class="loadingio-spinner-blocks-f3haiw2v97l">
    <div class="ldio-p2iphlr4dhn">
      <div style="left: 18px; top: 18px; animation-delay: 0s"></div>
      <div style="left: 42px; top: 18px; animation-delay: 0.12376237623762376s"></div>
      <div style="left: 66px; top: 18px; animation-delay: 0.24752475247524752s"></div>
      <div style="left: 18px; top: 42px; animation-delay: 0.8663366336633663s"></div>
      <div style="left: 66px; top: 42px; animation-delay: 0.3712871287128713s"></div>
      <div style="left: 18px; top: 66px; animation-delay: 0.7425742574257426s"></div>
      <div style="left: 42px; top: 66px; animation-delay: 0.6188118811881188s"></div>
      <div style="left: 66px; top: 66px; animation-delay: 0.49504950495049505s"></div>
    </div>
  </div>
</template>
<style scoped>
@keyframes ldio-p2iphlr4dhn {
  0% {
    background: var(--c-light-1);
  }
  12.5% {
    background: var(--c-light-1);
  }
  12.625% {
    background: hsl(var(--c-light-1-hsl), 50%);
  }
  100% {
    background: hsl(var(--c-light-1-hsl), 50%);
  }
}

.ldio-p2iphlr4dhn div {
  position: absolute;
  width: 16px;
  height: 16px;
  background: var(--c-light-2);
  animation: ldio-p2iphlr4dhn 0.99s linear infinite;
}

.loadingio-spinner-blocks-f3haiw2v97l {
  width: 32px;
  height: 32px;
  display: block;
  overflow: hidden;
  background: none;
}

.ldio-p2iphlr4dhn {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.32);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-p2iphlr4dhn div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>
